name: jimtl_localazy
description: Localazy support for jimtl remote translations
version: 0.0.3
homepage: https://github.com/jaumard/jimtl
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ">=1.8.0 <2.0.0"
  collection: ">=1.15.0 <2.0.0"
  http: "^1.2.2"
  jimtl:
    git:
      url: https://github.com/Elr03/jimtl.git
      path: packages/jimtl

dev_dependencies:
  test: ^1.16.8