name: jimtl_localazy
description: Localazy support for jimtl remote translations
version: 0.0.3
homepage: https://github.com/jaumard/jimtl

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ">=1.8.0 <2.0.0"
  collection: ">=1.15.0 <2.0.0"
  http: ">=0.13.4 <2.0.0"
  jimtl: ">=0.0.5 <1.0.0"
  #path: ../jimtl

dev_dependencies:
  test: ^1.16.8